import { GetEnrollmentsNewCardFormApiResponse } from "../interfaces/get-enrollments-newcardform.interface";

export const getEnrollmentsNewCardFormApiResponse: GetEnrollmentsNewCardFormApiResponse =
  {
    data: {
      transactionType: {
        show: true,
        label: "Tipo de transacci\u00f3n",
        value: "D\u00e9bito autom\u00e1tico",
        formattedValue: "D\u00e9bito autom\u00e1tico",
      },
      accountNumber: {
        show: true,
        label: "N\u00famero de cuenta",
        value: "57490034",
        formattedValue: "57490034",
      },
      accountToEnroll: {
        show: true,
        label: "Cuenta a inscribir",
        value: "14199183",
        formattedValue: "14199183",
      },
      invoiceAmount: {
        show: true,
        label: "Monto mensual",
        value: "",
        formattedValue: "",
      },
    },
    config: {
      title: {
        value:
          "OneApp Convergent Autopayment Init transaction and get summary Block",
        show: false,
      },
      description: "",
      footer: "",
      tokenizedCards: [
        {
          tokenizedCardId: {
            value: 55036,
            show: false,
            label: "tokenizedCardId",
            formattedValue: "55036",
          },
          maskedCreditCardNumber: {
            value: "222100XXXXXX0009",
            show: true,
            label: "maskedCreditCardNumber",
            formattedValue: "**** 0009",
          },
          cardBrand: {
            value: "UNKNOW",
            show: true,
            label: "cardBrand",
            formattedValue: "UNKNOW",
          },
          expirationMonth: {
            value: 3,
            show: true,
            label: "expirationMonth",
            formattedValue: "03",
          },
          expirationYear: {
            value: 2033,
            show: true,
            label: "expirationYear",
            formattedValue: "2033",
          },
          extraValidationRequired: {
            value: true,
            show: true,
            label: "extraValidationRequired",
            formattedValue: true,
          },
          cardLabel: {
            label: "cardLabel",
            value: "",
            formattedValue: "",
            show: false,
          },
        },
        {
          tokenizedCardId: {
            value: 59525,
            show: false,
            label: "tokenizedCardId",
            formattedValue: "59525",
          },
          maskedCreditCardNumber: {
            value: "411111XXXXXX2222",
            show: true,
            label: "maskedCreditCardNumber",
            formattedValue: "**** 2222",
          },
          cardBrand: {
            value: "VISA",
            show: true,
            label: "cardBrand",
            formattedValue: "VISA",
          },
          expirationMonth: {
            value: 2,
            show: true,
            label: "expirationMonth",
            formattedValue: "02",
          },
          expirationYear: {
            value: 2024,
            show: true,
            label: "expirationYear",
            formattedValue: "2024",
          },
          extraValidationRequired: {
            value: true,
            show: true,
            label: "extraValidationRequired",
            formattedValue: true,
          },
          cardLabel: {
            label: "cardLabel",
            value: "",
            formattedValue: "",
            show: false,
          },
        },
        {
          tokenizedCardId: {
            value: 60250,
            show: false,
            label: "tokenizedCardId",
            formattedValue: "60250",
          },
          maskedCreditCardNumber: {
            value: "411111XXXXXX1111",
            show: true,
            label: "maskedCreditCardNumber",
            formattedValue: "**** 1111",
          },
          cardBrand: {
            value: "VISA",
            show: true,
            label: "cardBrand",
            formattedValue: "VISA",
          },
          expirationMonth: {
            value: 8,
            show: true,
            label: "expirationMonth",
            formattedValue: "08",
          },
          expirationYear: {
            value: 2078,
            show: true,
            label: "expirationYear",
            formattedValue: "2078",
          },
          extraValidationRequired: {
            value: true,
            show: true,
            label: "extraValidationRequired",
            formattedValue: true,
          },
          cardLabel: {
            label: "cardLabel",
            value: "",
            formattedValue: "",
            show: false,
          },
        },
        {
          tokenizedCardId: {
            value: 50503,
            show: false,
            label: "tokenizedCardId",
            formattedValue: "50503",
          },
          maskedCreditCardNumber: {
            value: "401288XXXXXX1881",
            show: true,
            label: "maskedCreditCardNumber",
            formattedValue: "**** 1881",
          },
          cardBrand: {
            value: "VISA",
            show: true,
            label: "cardBrand",
            formattedValue: "VISA",
          },
          expirationMonth: {
            value: 12,
            show: true,
            label: "expirationMonth",
            formattedValue: "12",
          },
          expirationYear: {
            value: 2024,
            show: true,
            label: "expirationYear",
            formattedValue: "2024",
          },
          extraValidationRequired: {
            value: true,
            show: true,
            label: "extraValidationRequired",
            formattedValue: true,
          },
          cardLabel: {
            label: "cardLabel",
            value: "",
            formattedValue: "",
            show: false,
          },
        },
        {
          tokenizedCardId: {
            value: 50506,
            show: false,
            label: "tokenizedCardId",
            formattedValue: "50506",
          },
          maskedCreditCardNumber: {
            value: "555555XXXXXX4444",
            show: true,
            label: "maskedCreditCardNumber",
            formattedValue: "**** 4444",
          },
          cardBrand: {
            value: "MASTERCARD",
            show: true,
            label: "cardBrand",
            formattedValue: "MASTERCARD",
          },
          expirationMonth: {
            value: 12,
            show: true,
            label: "expirationMonth",
            formattedValue: "12",
          },
          expirationYear: {
            value: 2025,
            show: true,
            label: "expirationYear",
            formattedValue: "2025",
          },
          extraValidationRequired: {
            value: true,
            show: true,
            label: "extraValidationRequired",
            formattedValue: true,
          },
          cardLabel: {
            label: "cardLabel",
            value: "",
            formattedValue: "",
            show: false,
          },
        },
      ],
      actions: {
        initSubmit: {
          label: "Continuar",
          show: true,
          type: "button",
          url: "",
        },
        initCancel: {
          label: "Cancelar",
          show: true,
          type: "button",
          url: "",
        },
        summarySubmit: {
          label: "Activar",
          show: true,
          type: "button",
          url: "",
        },
        summaryCancel: {
          label: "Cancelar",
          show: true,
          type: "button",
          url: "",
        },
      },
      forms: {
        newCardForm: {
          description: {
            show: true,
            label: "Allowed credits cards",
            details: "*Only cards issued in the United States are accepted",
            value: "",
          },
          identificationType: {
            defaultValue: '',
            show: false,
            label: "Tipo de identificaci\u00f3n",
            placeholder: "",
            type: "select",
            format: "",
            options: [
              {
                value: "",
                label: false,
              },
            ],
            validations: {
              required: false,
              minLength: "0",
              maxLength: "128",
            },
            value: "",
          },
          identificationNumber: {
            show: false,
            label: "N\u00famero de identificaci\u00f3n",
            placeholder: "",
            type: "number",
            format: "",
            validations: {
              required: false,
              minLength: "0",
              maxLength: "128",
            },
            value: "",
          },
          nameCard: {
            show: true,
            label: "Nombre del titular",
            placeholder: "",
            type: "text",
            format: "",
            validations: {
              required: false,
              minLength: "0",
              maxLength: "128",
            },
            value: "",
          },
          numberCard: {
            show: true,
            validations: {
              allowedCreditCards: ["AMEX", "VISA", "MASTERCARD"],
              required: false,
              minLength: "12",
              maxLength: "19",
            },
            label: "N\u00famero completo de la tarjeta",
            placeholder: "0000 0000 0000 0000",
            type: "text",
            format: "",
            value: "",
          },
          expirationDateMonth: {
            show: false,
            label: "Fecha de expiraci\u00f3n mes",
            placeholder: "MM/YY",
            type: "select",
            format: "MM",
            options: [
              {
                value: "",
                label: false,
              },
            ],
            validations: {
              required: true,
              minLength: "0",
              maxLength: "128",
            },
            value: "",
          },
          expirationDateYear: {
            show: false,
            label: "Fecha de expiraci\u00f3n year",
            placeholder: "",
            type: "select",
            format: "YY",
            options: [
              {
                value: "",
                label: false,
              },
            ],
            validations: {
              required: true,
              minLength: "0",
              maxLength: "128",
            },
            value: "",
          },
          expirationDate: {
            show: true,
            label: "Fecha de expiraci\u00f3n",
            placeholder: "",
            type: "text",
            format: "MM/YY",
            validations: {
              required: true,
              minLength: "0",
              maxLength: "5",
            },
            value: "",
          },
          numberQuotas: {
            defaultValue: '',
            show: false,
            label: "Cuotas",
            placeholder: "",
            type: "select",
            format: "",
            options: [
              {
                value: "",
                label: false,
              },
            ],
            validations: {
              required: false,
              minLength: "0",
              maxLength: "0",
            },
            value: "",
          },
          cvv: {
            show: true,
            label: "C\u00f3digo de seguridad",
            placeholder: "000",
            type: "password",
            format: "",
            validations: {
              required: false,
              minLength: "3",
              maxLength: "4",
            },
            value: "",
          },
          phone: {
            show: false,
            label: "Tel\u00e9fono celular",
            placeholder: "",
            type: "text",
            format: "",
            validations: {
              required: false,
              minLength: "8",
              maxLength: "128",
            },
            value: "",
          },
          address: {
            show: false,
            label: "Direcci\u00f3n",
            placeholder: "",
            type: "text",
            format: "",
            validations: {
              required: false,
              minLength: "0",
              maxLength: "128",
            },
            value: "",
          },
          email: {
            show: false,
            label: "Correo electr\u00f3nico",
            placeholder: "Correo electr\u00f3nico",
            type: "text",
            format: "",
            validations: {
              required: false,
              minLength: "5",
              maxLength: "128",
            },
            disableOnFormRequired: {
              tokenized: 0,
              invoices_autopayments: 0,
              invoices: 0,
              autopackets: 0,
              packets: 0,
              topups: 0,
            },
            hideHe: 0,
            hidePP: 1,
            value: "",
          },
          rememberCard: {
            show: true,
            label: "Quiero guardar mis datos para futuros pagos",
            placeholder: "",
            type: "checkbox",
            format: "",
            validations: {
              required: false,
              minLength: "0",
              maxLength: "0",
            },
            value: "",
          },
          country: {
            show: false,
            label: "Pais",
            placeholder: "US",
            type: "text",
            format: "",
            validations: {
              required: false,
              minLength: "2",
              maxLength: "32",
            },
            value: "",
          },
          city: {
            show: false,
            label: "Ciudad",
            placeholder: "Mountain View",
            type: "text",
            format: "",
            validations: {
              required: false,
              minLength: "2",
              maxLength: "32",
            },
            value: "",
          },
          state: {
            show: false,
            label: "Estado",
            placeholder: "CA",
            type: "text",
            format: "",
            validations: {
              required: false,
              minLength: "2",
              maxLength: "2",
            },
            value: "",
          },
          postalCode: {
            show: false,
            label: "C\u00f3digo Postal",
            placeholder: "94043",
            type: "text",
            format: "",
            validations: {
              required: false,
              minLength: "2",
              maxLength: "32",
            },
            value: "",
          },
          enrollMe: {
            show: true,
            label: "Pago automatico tarjeta de credito y debito",
            placeholder: "",
            type: "checkbox",
            format: "",
            validations: {
              required: false,
              minLength: "0",
              maxLength: "0",
            },
            hideHe: 0,
            hidePP: 0,
            hideB2b: 1,
            value: "",
          },
        },
      },
      summary: {
        title: {
          value: "Resumen",
          show: true,
        },
        description:
          "Revisa tus datos antes de activar tu afiliaci\u00f3n a d\u00e9bito autom\u00e1tico",
        note: "* El monto est\u00e1 sujeto a cambios por servicios adicionales contratados durante el mes.",
        footer:
          "Al presionar ACTIVAR est\u00e1s aceptando los @t\u00e9rminos_y_condiciones",
      },
      termsAndConditions: {
        prefix: "Al presionar ACTIVAR est\u00e1s aceptando los ",
        label: "t\u00e9rminos y condiciones",
        url: "/",
        externalUrl: "",
        type: "link",
        show: true,
      },
    },
    meta: {
      id: "14199183",
      idType: "subscribers",
      params: {
        _format: "json",
      },
      businessUnit: "recurringpayment",
      category: "home",
      cache: 0,
      expirationCache: 1692617064,
    },
  };
