import { GetOrderDetailApiResponse } from "../interfaces/get-order-detail-api-response.interface";

export const getOrderDetailApiResponse: GetOrderDetailApiResponse = {
  data: {
    msisdn: {
      label: 'Número de línea',
      value: '123456789',
      formattedValue: '123456789',
      show: true,
    },
    amount: {
      label: 'Valor',
      value: '5000',
      formattedValue: '$ 5.000',
      show: true,
    },
    detail: {
      label: 'Detalle compra:',
      formattedValue: 'Recarga de saldo',
      show: true,
    },
  },
  config: {
    title: {
      value: 'Metodos de Pago para Recarga (Recharge Order Details) 2.0',
      show: false,
    },
    description: '',
    footer: '',
    actions: {
      paymentMethods: [
        {
          coreBalance: {
            paymentMethodName: 'coreBalance',
            label: 'Saldo de Recarga',
            url: '/',
            type: 'link',
            show: true,
            isRecurrent: false,
            otpRequired: true,
            weight: '1',
            description: {
              label: 'Tu saldo:',
              formattedValue: '$ 0.01',
              show: true,
              value: {
                amount: 0.01,
                currencyId: 'USD',
              },
              validForPurchase: false,
            },
            confirmation: {
              confirmationTitle: {
                label: 'Resumen',
                show: true,
              },
              message: {
                label: 'No tienes saldo suficiente para realizar esta compra, te invitamos a realizar una recarga o pagar con tarjeta de crédito.',
                show: true,
              },
              orderDetailsTitle: {
                label: 'Datos de pago:',
                show: true,
              },
              typeProduct: {
                label: 'Tipo de producto:',
                show: true,
              },
              paymentMethodsTitle: {
                label: 'Forma de pago:',
                show: true,
              },
              paymentMethod: {
                label: 'Método de pago:',
                formattedValue: 'Saldo de recargas',
                show: true,
              },
              coreBalancePayment: {
                label: 'Saldo disponible:',
                show: true,
              },
              actions: {
                change: {
                  label: 'CAMBIAR',
                  url: '/',
                  type: 'link',
                  show: true,
                },
                cancel: {
                  label: 'CANCELAR',
                  url: '/',
                  type: 'link',
                  show: true,
                },
                purchase: {
                  label: 'COMPRAR',
                  url: '/',
                  type: 'link',
                  show: false,
                },
                termsOfServices: {
                  label: 'Al presionar COMPRAR estás aceptando los términos y condiciones.',
                  url: '/',
                  type: 'link',
                  show: true,
                },
              },
            },
          },
          invoiceCharge: {
            paymentMethodName: 'invoiceCharge',
            label: 'Cargo a Factura',
            url: '/',
            type: 'link',
            show: false,
            isRecurrent: false,
            description: {
              label: 'Cargo a Factura',
              show: true,
            },
            otpRequired: false,
            weight: '2',
            confirmation: {
              confirmationTitle: {
                label: 'Resumen',
                show: true,
              },
              message: {
                label: 'Se cargarán C$ 200 en tu siguiente factura',
                show: true,
              },
              orderDetailsTitle: {
                label: 'Datos de pago:',
                show: true,
              },
              productType: {
                label: 'Tipo de producto:',
                show: true,
              },
              paymentMethodTitle: {
                label: 'Forma de pago:',
                show: true,
              },
              paymentMethod: {
                label: 'Método de pago:',
                formattedValue: 'Cargo a factura',
                show: true,
              },
              actions: {
                cancel: {
                  label: 'CANCELAR',
                  url: '/',
                  type: 'link',
                  show: true,
                },
                purchase: {
                  label: 'COMPRAR',
                  url: '/',
                  type: 'link',
                  show: true,
                },
                termsOfServices: {
                  label: 'Al presionar COMPRAR estás aceptando los términos y condiciones.',
                  url: '/',
                  type: 'link',
                  show: true,
                },
              },
            },
          },
          Async_PSE: {
            paymentMethodName: 'Async_PSE',
            label: 'Tarjeta débito',
            description: {
              label: 'Recibe de regalo el 85% más de crédito',
              show: true,
            },
            url: '/',
            type: 'button',
            show: true,
            isRecurrent: true,
            optRequired: false,
            weight: '1',
          },
          creditCard: {
            paymentMethodName: 'creditCard',
            label: 'Tarjeta de débito/crédito',
            url: '/',
            type: 'button',
            show: true,
            isRecurrent: true,
            optRequired: false,
            weight: '3',
            description: {
              label: 'Descuento 20% si suscribes el paquete',
              show: true,
            },
          },
          Loan_Balance: {
            paymentMethodName: 'Loan_Balance',
            label: 'Adelanta saldo',
            url: '/',
            type: 'button',
            show: true,
            isRecurrent: true,
            optRequired: false,
            description: {
              label: '',
              show: false,
            },
            weight: '3',
          },
          Loan_Packets: {
            paymentMethodName: 'Loan_Packets',
            label: 'Préstamo',
            url: '/',
            type: 'link',
            show: false,
            isRecurrent: false,
            optRequired: false,
            weight: '5',
            description: {
              label: '',
              show: true,
            },
          },
          Async_Bancolombia: {
            paymentMethodName: 'Async_Bancolombia',
            label: 'Bancolombia',
            url: '/',
            type: 'button',
            show: true,
            isRecurrent: true,
            optRequired: false,
            description: {
              label: '',
              show: false,
            },
            weight: '4',
          },
          Async_Nequi: {
            paymentMethodName: 'Async_Nequi',
            isNative: true,
            label: 'Nequi',
            url: '/',
            type: 'button',
            show: true,
            isRecurrent: true,
            optRequired: false,
            description: {
              label: '',
              show: false,
            },
            weight: '5',
          },
          Async_Paypal: {
            paymentMethodName: 'Async_Paypal',
            label: 'Paypal',
            url: '/',
            type: 'button',
            show: true,
            isRecurrent: true,
            optRequired: false,
            description: {
              label: '',
              show: false,
            },
            weight: '4',
          },
          Async_Daviplata: {
            paymentMethodName: 'Async_Daviplata',
            label: 'Daviplata',
            url: '/',
            type: 'button',
            show: true,
            isRecurrent: true,
            optRequired: false,
            description: {
              label: '',
              show: false,
            },
            weight: '6',
          },
          tigoMoney: {
            paymentMethodName: 'tigoMoney',
            label: 'Tigo Money',
            url: '/',
            type: 'link',
            show: true,
            isRecurrent: true,
            optRequired: false,
            weight: '3',
            description: {
              label: '',
              show: false,
            },
          },
          qrPayment: {
            paymentMethodName: 'qrPayment',
            label: 'Pagos con QR',
            url: '/',
            type: 'link',
            show: true,
            isRecurrent: true,
            optRequired: false,
            weight: '3',
            description: {
              label: 'Crédito & Débito',
              show: true,
            },
          },
          bancardAsync: {
            paymentMethodName: 'bancardAsync',
            label: 'Tarjeta de Crédito',
            url: '/',
            type: 'button',
            show: true,
            isRecurrent: true,
            optRequired: false,
            weight: '7',
            description: {
              label: 'Amex, Diners, Discover y otros',
              show: true,
            },
          },
          bancard: {
            paymentMethodName: 'bancard',
            label: 'Registra tus tarjetas',
            url: '/',
            type: 'button',
            show: true,
            isRecurrent: true,
            optRequired: false,
            weight: '10',
            description: {
              label: 'Requerido para tarjeta de debito',
              show: true,
            },
          },
          Async_ClaveCard: {
            paymentMethodName: 'Async_ClaveCard',
            label: 'Tarjeta Clave',
            url: '/',
            type: 'button',
            show: true,
            isRecurrent: true,
            optRequired: false,
            weight: '10',
            description: {
              label: 'Requerido para tarjeta de debito',
              show: true,
            },
          },
          Async_Yappy: {
            paymentMethodName: 'Async_Yappy',
            label: 'Yappy',
            url: '/',
            type: 'button',
            show: true,
            isRecurrent: true,
            optRequired: false,
            weight: '10',
            description: {
              label: 'Requerido para tarjeta de debito',
              show: true,
            },
          },
          Async_bitcoins: {
            paymentMethodName: 'Async_bitcoins',
            label: 'Bitcoin',
            url: '/',
            type: 'button',
            show: true,
            isRecurrent: true,
            optRequired: false,
            description: {
              label: '',
              show: true,
            },
          },
          tigoMoney_Inv: {
            paymentMethodName: 'tigoMoney_Inv',
            label: 'Tigo Money',
            url: '/',
            type: 'button',
            show: true,
            description: {
              show: true,
              label: 'Introduce el número asociado a Tigo Money con el que deseas realizar el pago',
            },
            forms: {
              description: {
                show: true,
                value: 'Introduce el número asociado a Tigo Money con el que deseas realizar el pago',
              },
              payerAccount: {
                show: true,
                label: '',
                placeholder: '',
                type: 'phone',
                format: '',
                value: '',
                options: [
                  '78738427',
                  '72103895',
                  '72178068',
                  '72227280',
                  '72559783',
                  '72621675',
                  '72840551',
                  '72874214',
                  '72930888',
                  '74705632',
                  '74786047',
                  '74811299',
                  '74946246',
                  '74988823',
                  '75073231',
                  '75244163',
                  '75426234',
                  '75574672',
                  '75610518',
                  '75769028',
                  '75839377',
                  '76811577',
                  '76835832',
                  '77871721',
                  '78735823',
                  '78886838',
                  '78953925',
                  '79189178',
                  '79234643',
                  '79249703',
                  '79255113',
                  '79289936',
                  '79304336',
                  '79372240',
                  '79383753',
                  '79393306',
                  '79412100',
                  '79413367',
                  '79493097',
                  '79534720',
                  '79876465',
                  '79886382',
                  '72226267',
                  '72246113',
                  '74898138',
                  '78917540',
                  '79223274',
                ],
                validations: {
                  required: true,
                  minLength: '8',
                  maxLength: '8',
                },
              },
            },
          },
        },
      ],
    },
  },
  meta: {
    proid: 22222,
    cache: 0,
    expirationCache: 123123,
  },
};
