import { PostOrderDetailApiResponse } from "../interfaces/post-order-detail-api-response.interface";

export const postOrderDetailApiResponse: PostOrderDetailApiResponse = {
  data: {
    offerId: {
      label: 'ID Oferta',
      show: false,
      value: 588,
      formattedValue: '588',
    },
    accountNumber: {
      show: true,
      label: 'Número',
      value: '123456789',
      formattedValue: '123456789',
    },
    offerName: {
      label: 'Oferta',
      show: false,
      value: '1.6GB + WhatsApp, TikTok, Facebook ILIMITADO',
      formattedValue: '1.6GB + WhatsApp, TikTok, Facebook ILIMITADO',
    },
    description: {
      label: 'Descripción',
      show: true,
      value: '1.6GB + WhatsApp, TikTok, Facebook ILIMITADO',
      formattedValue: '1.6GB + WhatsApp, TikTok, Facebook ILIMITADO',
    },
    categoryName: {
      label: 'Categoria',
      show: false,
      value: 'INTERNET',
      formattedValue: 'INTERNET',
    },
    validity: {
      label: 'Vigencia',
      show: true,
      value: 3,
      formattedValue: '3 dias',
    },
    amount: {
      label: 'Valor',
      show: true,
      value: 15,
      formattedValue: 'Q15',
    },
    purchaseOrderId: {
      label: 'PurchaseOrderId',
      show: false,
      value: 'Encrypted preorder id',
      formattedValue: 'encrypted preorder Id',
    },
    productType: {
      label: 'Tipo de producto',
      show: true,
      value: '1.6GB + WhatsApp, TikTok, Facebook ILIMITADO',
      formattedValue: '1.6GB + WhatsApp, TikTok, Facebook ILIMITADO',
    },
    paymentMethod: {
      label: 'Método de pago:',
      show: true,
      value: 'TigoMoney',
      formattedValue: 'TigoMoney',
    },
    wallet: {
      label: 'Billetera:',
      show: true,
      value: 'Principal',
      formattedValue: 'Principal',
    },
    pinless: {
      value: false,
    },
    redirectUrl: {
      label: 'redirectURL',
      value: 'http://tgo.gt/tmyapm',
      formattedValue: 'http://tgo.gt/tmyapm',
      show: false,
    },
  },
  config: {
    title: {
      value: 'Inicializar compra de paquetes',
      show: false,
    },
    description: '',
    footer: '',
    isValidTigoMoneyAccount: false,
    confirmation: {
      otpTemplateId: '',
      confirmationTitle: {
        label: 'Resumen',
        show: true,
      },
      orderDetailsTitle: {
        label: 'Datos de pago:',
        show: true,
      },
      paymentMethodsTitle: {
        label: 'Forma de pago:',
        show: true,
      },
      invoiceDetails: {
        label: 'Datos de factura:test',
        show: true,
      },
      actions: {
        fulldescription: {
          label: 'más',
          show: true,
          type: 'link',
          url: '/',
        },
        change: {
          label: 'CAMBIAR',
          show: true,
          type: 'link',
          url: '/',
        },
        changeInvoiceDetails: {
          label: 'CAMBIAR',
          show: true,
          type: 'link',
          url: '/',
        },
        cancel: {
          label: 'CANCELAR',
          show: true,
          type: 'link',
          url: '/',
        },
        purchase: {
          label: 'PAGAR',
          show: true,
          type: 'link',
          url: '/',
        },
        termsOfServices: {
          label: 'Al presionar PAGAR estás aceptando los términos y condiciones.',
          show: true,
          type: 'link',
          url: '/',
        },
      },
    },
    params: {
      fingerPrint: {
        link: 'link pathh',
        integrate: 'Integration Path',
      },
      purchaseorderId: 'Pre-order Id',
    },
    cards: {
      tokenizedCards: [
        {
          tokenizedCardId: {
            value: 39234,
            show: false,
            label: 'tokenizedCardId',
            formattedValue: '39234',
          },
          maskedCreditCardNumber: {
            value: '555555XXXXXX4444',
            show: true,
            label: 'maskedCreditCardNumber',
            formattedValue: '**** 4444',
          },
          cardBrand: {
            value: 'MASTERCARD',
            show: true,
            label: 'cardBrand',
            formattedValue: 'MASTERCARD',
          },
          expirationMonth: {
            value: 11,
            show: true,
            label: 'expirationMonth',
            formattedValue: '11',
          },
          expirationYear: {
            value: 2023,
            show: true,
            label: 'expirationYear',
            formattedValue: '2023',
          },
          extraValidationRequired: {
            value: false,
            show: true,
            label: 'extraValidationRequired',
            formattedValue: false,
          },
          cardLabel: {
            label: 'cardLabel',
            value: '',
            formattedValue: '',
            show: false,
          },
        },
        {
          tokenizedCardId: {
            value: 59158,
            show: false,
            label: 'tokenizedCardId',
            formattedValue: '59158',
          },
          maskedCreditCardNumber: {
            value: '222100XXXXXX0009',
            show: true,
            label: 'maskedCreditCardNumber',
            formattedValue: '**** 0009',
          },
          cardBrand: {
            value: 'UNKNOW',
            show: true,
            label: 'cardBrand',
            formattedValue: 'UNKNOW',
          },
          expirationMonth: {
            value: 3,
            show: true,
            label: 'expirationMonth',
            formattedValue: '03',
          },
          expirationYear: {
            value: 2033,
            show: true,
            label: 'expirationYear',
            formattedValue: '2033',
          },
          extraValidationRequired: {
            value: true,
            show: true,
            label: 'extraValidationRequired',
            formattedValue: true,
          },
          cardLabel: {
            label: 'cardLabel',
            value: '',
            formattedValue: '',
            show: false,
          },
        },
        {
          tokenizedCardId: {
            value: 60137,
            show: false,
            label: 'tokenizedCardId',
            formattedValue: '60137',
          },
          maskedCreditCardNumber: {
            value: '411111XXXXXX1111',
            show: true,
            label: 'maskedCreditCardNumber',
            formattedValue: '**** 1111',
          },
          cardBrand: {
            value: 'VISA',
            show: true,
            label: 'cardBrand',
            formattedValue: 'VISA',
          },
          expirationMonth: {
            value: 9,
            show: true,
            label: 'expirationMonth',
            formattedValue: '09',
          },
          expirationYear: {
            value: 2077,
            show: true,
            label: 'expirationYear',
            formattedValue: '2077',
          },
          extraValidationRequired: {
            value: true,
            show: true,
            label: 'extraValidationRequired',
            formattedValue: true,
          },
          cardLabel: {
            label: 'cardLabel',
            value: '',
            formattedValue: '',
            show: false,
          },
        },
        {
          tokenizedCardId: {
            value: 54366,
            show: false,
            label: 'tokenizedCardId',
            formattedValue: '54366',
          },
          maskedCreditCardNumber: {
            value: '455644XXXXXX5481',
            show: true,
            label: 'maskedCreditCardNumber',
            formattedValue: '**** 5481',
          },
          cardBrand: {
            value: 'VISA',
            show: true,
            label: 'cardBrand',
            formattedValue: 'VISA',
          },
          expirationMonth: {
            value: 7,
            show: true,
            label: 'expirationMonth',
            formattedValue: '07',
          },
          expirationYear: {
            value: 2026,
            show: true,
            label: 'expirationYear',
            formattedValue: '2026',
          },
          extraValidationRequired: {
            value: true,
            show: true,
            label: 'extraValidationRequired',
            formattedValue: true,
          },
          cardLabel: {
            label: 'cardLabel',
            value: '',
            formattedValue: '',
            show: false,
          },
        },
      ],
    },
    forms:
      {
        newCardForm: {
          description: {
            show: true,
            label: 'Allowed credits cards',
            details: '*Only cards issued in the United States are accepted',
            value: '',
          },
          identificationType: {
            show: true,
            label: 'Documento',
            placeholder: '',
            type: 'select',
            format: '',
            options: [
              {
                value: 'CC',
                label: 'CC',
              },
              {
                value: 'CE',
                label: 'CE',
              },
              {
                value: 'NIT',
                label: 'NIT',
              },
            ],
            validations: {
              required: false,
              minLength: '0',
              maxLength: '128',
            },
            defaultValue: '',
          },
          identificationNumber: {
            show: true,
            label: 'Número de identificación',
            placeholder: '',
            type: 'number',
            format: '',
            validations: {
              required: false,
              minLength: '0',
              maxLength: '128',
            },
            defaultValue: '',
          },
          nameCard: {
            show: true,
            label: 'Nombre del titular',
            placeholder: '',
            type: 'text',
            format: '',
            validations: {
              required: false,
              minLength: '0',
              maxLength: '128',
            },
            value: '',
          },
          numberCard: {
            show: true,
            validations: {
              allowedCreditCards: ['AMEX', 'VISA', 'MASTERCARD'],
              required: false,
              minLength: '12',
              maxLength: '19',
            },
            label: 'Número completo de la tarjeta',
            placeholder: '0000 0000 0000 0000',
            type: 'text',
            format: '',
            value: '',
          },
          expirationDateMonth: {
            show: false,
            label: 'Fecha de expiración mes',
            placeholder: 'MM/YY',
            type: 'select',
            format: 'MM',
            options: [
              {
                value: '',
                label: '',
              },
            ],
            validations: {
              required: true,
              minLength: '0',
              maxLength: '128',
            },
            value: '',
          },
          expirationDateYear: {
            show: false,
            label: 'Fecha de expiración year',
            placeholder: '',
            type: 'select',
            format: 'YY',
            options: [
              {
                value: '',
                label: '',
              },
            ],
            validations: {
              required: true,
              minLength: '0',
              maxLength: '128',
            },
            value: '',
          },
          expirationDate: {
            show: true,
            label: 'Fecha de expiración',
            placeholder: '',
            type: 'text',
            format: 'MM/YY',
            validations: {
              required: true,
              minLength: '0',
              maxLength: '5',
            },
            value: '',
          },
          numberQuotas: {
            show: true,
            label: 'Cuotas',
            placeholder: '',
            type: 'select',
            format: '',
            options: [
              {
                value: '1',
                label: '1',
              },
              {
                value: '2',
                label: '2',
              },
              {
                value: '3',
                label: '3',
              },
              {
                value: '4',
                label: '4',
              },
              {
                value: '5',
                label: '5',
              },
              {
                value: '6',
                label: '6',
              },
              {
                value: '7',
                label: '7',
              },
              {
                value: '8',
                label: '8',
              },
              {
                value: '9',
                label: '9',
              },
              {
                value: '10',
                label: '10',
              },
              {
                value: '11',
                label: '11',
              },
              {
                value: '12',
                label: '12',
              },
            ],
            validations: {
              required: false,
              minLength: '0',
              maxLength: '2',
            },
            defaultValue: '1',
          },
          cvv: {
            show: true,
            label: 'Código de seguridad',
            placeholder: '000',
            type: 'password',
            format: '',
            validations: {
              required: false,
              minLength: '3',
              maxLength: '4',
            },
            value: '',
          },
          phone: {
            show: false,
            label: 'Teléfono celular',
            placeholder: '',
            type: 'text',
            format: '',
            validations: {
              required: false,
              minLength: '8',
              maxLength: '128',
            },
            value: '',
          },
          address: {
            show: true,
            label: 'Dirección',
            placeholder: '',
            type: 'text',
            format: '',
            validations: {
              required: false,
              minLength: '0',
              maxLength: '128',
            },
            defaultValue: '',
          },
          email: {
            show: false,
            label: 'Correo electrónico',
            placeholder: 'Correo electrónico',
            type: 'text',
            format: '',
            validations: {
              required: false,
              minLength: '5',
              maxLength: '128',
            },
            disableOnFormRequired: {
              tokenized: 0,
              invoices_autopayments: 0,
              invoices: 0,
              autopackets: 0,
              packets: 0,
              topups: 0,
            },
            hideHe: 0,
            hidePP: 1,
            value: '',
          },
          rememberCard: {
            show: true,
            label: 'Quiero guardar mis datos para futuros pagos',
            placeholder: '',
            type: 'checkbox',
            format: '',
            validations: {
              required: false,
              minLength: '0',
              maxLength: '0',
            },
            value: '',
          },
          country: {
            show: true,
            label: 'Pais',
            placeholder: 'US',
            type: 'text',
            format: '',
            validations: {
              required: false,
              minLength: '2',
              maxLength: '32',
            },
            value: '',
          },
          city: {
            show: true,
            label: 'Ciudad',
            placeholder: 'Mountain View',
            type: 'text',
            format: '',
            validations: {
              required: false,
              minLength: '2',
              maxLength: '32',
            },
            value: '',
          },
          state: {
            show: true,
            label: 'Estado',
            placeholder: 'CA',
            type: 'text',
            format: '',
            validations: {
              required: false,
              minLength: '2',
              maxLength: '2',
            },
            value: '',
          },
          postalCode: {
            show: true,
            label: 'Código Postal',
            placeholder: '94043',
            type: 'text',
            format: '',
            validations: {
              required: false,
              minLength: '2',
              maxLength: '32',
            },
            value: '',
          },
          enrollMe: {
            show: true,
            label: 'Pago automatico tarjeta de credito y debito',
            placeholder: '',
            type: 'checkbox',
            format: '',
            validations: {
              required: false,
              minLength: '0',
              maxLength: '0',
            },
            hideHe: 0,
            hidePP: 0,
            hideB2b: 1,
            value: '',
          },
        },
        billingDataForm: {
          fullname: {
            show: true,
            label: 'Nombre',
            placeholder: '',
            type: 'text',
            format: '',
            value: '',
            validations: {
              required: false,
              minLength: '0',
              maxLength: '128',
            },
          },
          nit: {
            show: true,
            label: 'NIT',
            placeholder: '',
            type: 'text',
            format: '',
            value: '',
            validations: {
              required: false,
              minLength: '0',
              maxLength: '128',
            },
          },
          identificationNumber: {
            show: true,
            label: 'Identification',
            placeholder: '',
            type: 'text',
            format: '',
            value: '',
            validations: {
              required: false,
              minLength: '0',
              maxLength: '128',
            },
          },
          email: {
            show: true,
            label: 'Correo electrónico',
            placeholder: '',
            type: 'text',
            format: '',
            value: 'amckenna@mobiquityinc.com',
            validations: {
              required: true,
              minLength: '0',
              maxLength: '128',
            },
          },
          address: {
            show: true,
            label: 'Dirección',
            placeholder: '',
            type: 'text',
            format: '',
            value: '',
            validations: {
              required: false,
              minLength: '0',
              maxLength: '40',
            },
          },
        },
        tigoMoneyForm: {
          code: {
            show: true,
            label: 'Inserte su PIN de Tigo Money',
            placeholder: 'PIN',
            type: 'password',
            format: '',
            value: '',
            validations: {
              required: true,
              minLength: '4',
              maxLength: '4',
            },
          },
        },
        infoMessage: {
          description: {
            show: true,
            value: 'No tienes una cuenta Tigomoney con esta línea, Selecciona otro  método de pago o Registrate en Tigo Money.',
          },
          actions: {
            change: {
              label: 'Cambiar Método',
              show: true,
              type: 'button',
              url: '/',
            },
            register: {
              label: 'Registrarme',
              show: true,
              type: 'button',
              url: 'http://tgo.gt/tmyapm',
            },
          },
        },
      },
    
    actions: {
      submit: {
        label: 'Continuar',
        show: true,
        type: 'button',
        url: '',
      },
      cancel: {
        label: 'Cancelar',
        show: true,
        type: 'button',
        url: '',
      },
      login: {
        label: 'Usar cuentas guardadas',
        show: false,
        type: 'button',
        url: '',
      },
    },
    termsAndConditions: {
      prefix: 'Al presionar CONTINUAR estás aceptando los ',
      label: 'términos y condiciones',
      url: '/',
      externalUrl: '',
      type: 'link',
      show: true,
    },
  },
  meta: {
    id: 'account number',
    idType: 'subscribers',
    params: {
      targetMsisdn: 'target msisdn',
      _format: 'json',
    },
    businessUnit: 'payment',
    category: 'mobile',
    cache: 0,
    expirationCache: 'expiration',
  },
};
