AWSTemplateFormatVersion: 2010-09-09
Description: v1.0.0 | MiTigo | master | Master Cloudformation Template
Parameters:
  CostCenter:
    Description: Cost Center
    Type: String
    Default: caas-frontend
  Environment:
    Description: 'Env type: Dev, QA, Prod, etc.'
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
  StackURL:
    Description: Source URL+Stack Version WITHOUT trailing /
    Type: String

Resources:
  CaasFrontendS3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${StackURL}/sub-s3-crr.yml'
      Parameters:
        Environment: !Ref Environment
      Tags:
      - Key: Cost Center
        Value: !Ref CostCenter
      - Key: Stack
        Value: !Ref Environment
      - Key: Name
        Value: !Sub ${CostCenter}-${Environment}-S3Stack-crr

  CaasFrontendKmsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${StackURL}/sub-kms-crr.yml'
      Parameters:
        Environment: !Ref Environment
        CostCenter: !Ref CostCenter
      Tags:
      - Key: Cost Center
        Value: !Ref CostCenter
      - Key: Stack
        Value: !Ref Environment
      - Key: Name
        Value: !Sub ${CostCenter}-${Environment}-crr-KmsStack
      
