AWSTemplateFormatVersion: 2010-09-09
Description: v1.0.0 | Caas Frontend | KMS Key | Master Cloudformation Template
Parameters:
  CostCenter:
    Description: Cost Center
    Type: String
    Default: caas-frontend
  Environment:
    Description: 'Env type: Dev, QA, Prod, etc.'
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - uat
      - prod

Resources:
  CaasFrontendKmsKeyCRR:
      Type: AWS::KMS::Key
      Properties:
        Description: KMS Key for Encryption
        KeyPolicy:
          Version: 2012-10-17
          Id: root-permission-default
          Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':root' ] ]
            Action: 'kms:*'
            Resource: '*'
        Tags:
        - Key: Cost Center
          Value: !Ref CostCenter
        - Key: Stack
          Value: !Ref Environment
        - Key: Name
          Value: !Sub '${CostCenter}-${Environment}-crr-KMSKey'
  CaasFrontendKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/CaasFrontendKMSKey-${Environment}-crr'
      TargetKeyId: !Ref CaasFrontendKmsKeyCRR
Outputs:
  CaasFrontendKmsKeyCRRId:
    Description: Key Id of the Encryption KMS key
    Value: !Ref CaasFrontendKmsKeyCRR
