export enum PAYMENT_METHOD_TYPE {
  Saldo = 'coreBalance',
  CreditCard = 'creditCard',
  LoanPackets = 'Loan_Packets',
  LoanBalance = 'Loan_Balance',
  PSE = 'Async_PSE',
  Nequi = 'Async_Nequi',
  Bancolombia = 'Async_Bancolombia',
  Wompi = 'Async_Wompi',
  InvoiceCharge = 'invoiceCharge',
  FreePacket = 'freePacket',
  InvoiceChargeSecurity = 'invoiceChargeSecurity',
  EmergencyLoan = 'emergencyLoan',
  AsyncTigoMoney = 'Async_TigoMoney',
  TigoMoney = 'tigoMoney',
  Async_TigoMoney_Inv = 'Async_TigoMoney_Inv',
  TigoMoney_Inv = 'tigoMoney_Inv',
  Bancard = 'bancard',
  BancardAsync = 'bancardAsync',
  Async_ClaveCard = 'Async_ClaveCard',
  Async_bitcoins = 'Async_bitcoins',
  Async_Daviplata = 'Async_Daviplata',
  QrPayment = 'qrPayment',
  TigoQrPos = 'tigoQrPos',
  Async_Yappy = 'Async_Yappy',
}
