/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WcAutoPayment {
        "wcData": string;
    }
    interface WcPaymentComponent {
        "wcData": string;
    }
    interface WcSubscriptionsComponent {
        "wcData": string;
    }
}
export interface WcAutoPaymentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWcAutoPaymentElement;
}
export interface WcPaymentComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWcPaymentComponentElement;
}
export interface WcSubscriptionsComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWcSubscriptionsComponentElement;
}
declare global {
    interface HTMLWcAutoPaymentElement extends Components.WcAutoPayment, HTMLStencilElement {
    }
    var HTMLWcAutoPaymentElement: {
        prototype: HTMLWcAutoPaymentElement;
        new (): HTMLWcAutoPaymentElement;
    };
    interface HTMLWcPaymentComponentElement extends Components.WcPaymentComponent, HTMLStencilElement {
    }
    var HTMLWcPaymentComponentElement: {
        prototype: HTMLWcPaymentComponentElement;
        new (): HTMLWcPaymentComponentElement;
    };
    interface HTMLWcSubscriptionsComponentElement extends Components.WcSubscriptionsComponent, HTMLStencilElement {
    }
    var HTMLWcSubscriptionsComponentElement: {
        prototype: HTMLWcSubscriptionsComponentElement;
        new (): HTMLWcSubscriptionsComponentElement;
    };
    interface HTMLElementTagNameMap {
        "wc-auto-payment": HTMLWcAutoPaymentElement;
        "wc-payment-component": HTMLWcPaymentComponentElement;
        "wc-subscriptions-component": HTMLWcSubscriptionsComponentElement;
    }
}
declare namespace LocalJSX {
    interface WcAutoPayment {
        "onLoading"?: (event: WcAutoPaymentCustomEvent<any>) => void;
        "onWcLoading"?: (event: WcAutoPaymentCustomEvent<any>) => void;
        "onWcMessage"?: (event: WcAutoPaymentCustomEvent<any>) => void;
        "onWcRefreshToken"?: (event: WcAutoPaymentCustomEvent<any>) => void;
        "onWcSegment"?: (event: WcAutoPaymentCustomEvent<any>) => void;
        "wcData"?: string;
    }
    interface WcPaymentComponent {
        "onWcLoading"?: (event: WcPaymentComponentCustomEvent<any>) => void;
        "onWcMessage"?: (event: WcPaymentComponentCustomEvent<any>) => void;
        "onWcRefreshToken"?: (event: WcPaymentComponentCustomEvent<any>) => void;
        "onWcSegment"?: (event: WcPaymentComponentCustomEvent<any>) => void;
        "onWcTransactionClosed"?: (event: WcPaymentComponentCustomEvent<any>) => void;
        "onWcTransactionFinished"?: (event: WcPaymentComponentCustomEvent<any>) => void;
        "wcData"?: string;
    }
    interface WcSubscriptionsComponent {
        "onLoading"?: (event: WcSubscriptionsComponentCustomEvent<any>) => void;
        "onWcLoading"?: (event: WcSubscriptionsComponentCustomEvent<any>) => void;
        "onWcMessage"?: (event: WcSubscriptionsComponentCustomEvent<any>) => void;
        "onWcRefreshToken"?: (event: WcSubscriptionsComponentCustomEvent<any>) => void;
        "onWcSegment"?: (event: WcSubscriptionsComponentCustomEvent<any>) => void;
        "wcData"?: string;
    }
    interface IntrinsicElements {
        "wc-auto-payment": WcAutoPayment;
        "wc-payment-component": WcPaymentComponent;
        "wc-subscriptions-component": WcSubscriptionsComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wc-auto-payment": LocalJSX.WcAutoPayment & JSXBase.HTMLAttributes<HTMLWcAutoPaymentElement>;
            "wc-payment-component": LocalJSX.WcPaymentComponent & JSXBase.HTMLAttributes<HTMLWcPaymentComponentElement>;
            "wc-subscriptions-component": LocalJSX.WcSubscriptionsComponent & JSXBase.HTMLAttributes<HTMLWcSubscriptionsComponentElement>;
        }
    }
}
